name: telogator2-demo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - biopython>=1.82
  - matplotlib
  - numpy
  - scipy
  - pysam
  - pywavelets
  - pandas
  - openpyxl
  - seaborn
  - cairosvg
  - statsmodels
  - ipykernel
  - jupyter_core
  - Levenshtein
  - inputimeout
  - tqdm

